// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WEB_API_KEY',
    appId: '1:822958082668:web:94dc2718e9efab28da2649',
    messagingSenderId: '822958082668',
    projectId: 'villavibe-ff644',
    authDomain: 'villavibe-ff644.firebaseapp.com',
    storageBucket: 'villavibe-ff644.firebasestorage.app',
    measurementId: 'G-QDW34TM4W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_ANDROID_API_KEY',
    appId: '1:822958082668:android:c9e8b36d41d97981da2649',
    messagingSenderId: '822958082668',
    projectId: 'villavibe-ff644',
    storageBucket: 'villavibe-ff644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_IOS_API_KEY',
    appId: '1:822958082668:ios:ec20de0efc72418dda2649',
    messagingSenderId: '822958082668',
    projectId: 'villavibe-ff644',
    storageBucket: 'villavibe-ff644.firebasestorage.app',
    iosBundleId: 'com.example.villavibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_MACOS_API_KEY',
    appId: '1:822958082668:ios:ec20de0efc72418dda2649',
    messagingSenderId: '822958082668',
    projectId: 'villavibe-ff644',
    storageBucket: 'villavibe-ff644.firebasestorage.app',
    iosBundleId: 'com.example.villavibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_FIREBASE_WINDOWS_API_KEY',
    appId: '1:822958082668:web:b28544eaf5f08af3da2649',
    messagingSenderId: '822958082668',
    projectId: 'villavibe-ff644',
    authDomain: 'villavibe-ff644.firebaseapp.com',
    storageBucket: 'villavibe-ff644.firebasestorage.app',
    measurementId: 'G-97Q6E38WEV',
  );

}